# file: postgresql/tasks/extensions/postgis.yml

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_facts['distribution_release'] }}.yml"
    - "../vars/empty.yml"

- name: PostgreSQL | Extensions | Make sure the postgis extensions are installed | Debian
  apt:
    name: "{{ postgresql_ext_postgis_deps }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  when: ansible_facts['os_family'] == "Debian"
  notify:
    - restart postgresql

- name: PostgreSQL | Extensions | Make sure the postgis extensions are installed | RedHat
  yum:
    name: "{{ postgresql_ext_postgis_deps }}"
    state: present
    update_cache: yes
  when: ansible_facts['pkg_mgr'] == "yum" and ansible_facts['os_family'] == "RedHat"
  notify:
    - restart postgresql

- name: PostgreSQL | Extensions | Make sure the postgis extensions are installed | Fedora
  dnf:
    name: "{{ postgresql_ext_postgis_deps }}"
    state: present
  when: ansible_facts['pkg_mgr'] == "dnf" and ansible_facts['distribution'] == "Fedora"
  notify:
    - restart postgresql
